#  Comments only
import time

import requests
import Fwapi
import time
'''
1406211977
'''
class Comments:
    def __init__(self, list):
        self._list = list
        self.comment_list = []

    def get_comments(self):
        for list in self._list:
            print(list[0], '-', list[2])
            url = 'https://music.163.com/api/v1/resource/comments/R_SO_4_' + str(list[1]) + '?limit=20&offset=0'
            response = requests.get(url).text
            response = response.replace('false', 'False')
            response = response.replace('true', 'True')
            response = response.replace('null', '""')
            a = eval(response)
            try:
                for i in range(30):
                    print(a['hotComments'][i]['content'])
                    print('')
            except IndexError:
                time.sleep(3)
                print('\n')
                pass
print('Time is:'+time.strftime("%Y-%m-%d %H:%M:%S", time.localtime()))
print('Generated by FwMusic v.2.0-beta9c')
playlist = Fwapi.Playlist_v2(13636082756)
playlist.get_details()
id_list = playlist.playlist_songs
#print(playlist.playlist_songs)
comments = Comments(id_list)
comments.get_comments()
